#ifndef TCONFIG_H
#define TCONFIG_H

#define TINYOS_PRO_COUNT 32
#define TINYOS_SLICE_MAX 10
#define TINYOS_IDLETASK_STACK_SIZE 1024

#define TINYOS_TIMERTASK_STACK_SIZE 1024
#define TINYOS_TIMERTASK_PRIO 1

#define TINYOS_SYSTICK_MS   10

#define TINYOS_ENABLE_SEM 						1
#define TINYOS_ENABLE_MUTEX 					1
#define TINYOS_ENABLE_FLAGGROUP  			1
#define TINYOS_ENABLE_MBOX		 				1
#define TINYOS_ENABLE_MEMBLOCK				1
#define TINYOS_ENABLE_TIMER       		1
#define TINYOS_ENABLE_CPUUSAGE_STAT  	1
#define TINYOS_ENABLE_HOOKS						1

#endif
